let games = [{"Game_Title":"Prince of Persia","Publisher":"Broaderbund","Year_Published":1990,"Description":"While the Sultan of Persia is fighting a war in a foreign country, his Grand Vizier Jaffar orchestrates a coup d'etat.","Avatar":"img/prince.jpg?size=50x50&set=set1","iframe_URL":"https://archive.org/embed/msdos_Prince_of_Persia_1990"},


{"Game_Title":"Super Street Fighter II","Publisher":"Capcom","Year_Published":1996,"Description":'Super Street Fighter II is a sequel to Street Fighter II Turbo and Street Fighter II Championship. The game features four new characters and stages, making a total of sixteen playable.',"Avatar":"img/Super Street Fighter II Turbo_3.png?size=50x50&set=set1","iframe_URL":'https://archive.org/embed/msdos_Super_Street_Fighter_II_1996'},

{"Game_Title":"Batman Returns","Publisher":"SEGA","Year_Published":1993,"Description":"The Genesis title based on Batman Returns is a platform game in which the Dark Knight must traverse five action-filled levels on his way to confront the Penguin.","Avatar":"img/batman-returns-ss5.png?size=50x50&set=set1","iframe_URL":"https://archive.org/embed/msdos_Batman_Returns_1993"},


{"Game_Title":"Donkey Kong","Publisher":"Atarisoft","Year_Published":1983,"Description":"Released in the arcades in 1981, Donkey Kong was not only Nintendo's first real smash hit for the company, but marked the introduction for two of their most popular mascots: Mario (originally 'Jumpman') and Donkey Kong.","Avatar":"img/donkey-kong_3.gif?size=50x50&set=set1","iframe_URL":"https://archive.org/embed/msdos_Donkey_Kong_1983"},

{"Game_Title":"SimAnt","Publisher":"Maxis Software Inc.","Year_Published":1991,"Description":"SimAnt explores the detail of the lives of ants, as you take full control of an ant colony. Build up your colony to conquer the other colonies in the yard. Foes include spiders and humans - make their lives a misery by invading their homes.","Avatar":"img/Sim Ant_3.png?size=50x50&set=set1","iframe_URL":"https://archive.org/embed/msdos_SimAnt_-_The_Electronic_Ant_Colony_1991"},

{"Game_Title":"Star Wars","Publisher":"Broaderbund Software","Year_Published":1988,"Description":"Star Wars is a first-person shooter based around the final scenes of the original Star Wars film. It first appeared for arcade coin-operated machines and was subsequently converted to other gaming platforms.","Avatar":"img/Star Wars - The Arcade Game_3.png?size=50x50&set=set1","iframe_URL":"https://archive.org/embed/msdos_Star_Wars_1988"},

{"Game_Title":"Dragon's Lair","Publisher":"Sullivan Bluth Interactive","Year_Published":1989,"Description":"Dirk the Daring was a heroic, if clumsy knight. When Princess Daphne was kidnapped by the dragon, Singe, and taken to his castle, Dirk set out to rescue her.","Avatar":"img/dragons-lair_2.gif?size=50x50&set=set1","iframe_URL": src="https://archive.org/embed/msdos_Dragons_Lair_1993_1993"},

{"Game_Title":"Double Dragon","Publisher":"Techno Japan Corp","Year_Published":1988,"Description":"Set in a post-apocalyptic New York, Double Dragon is the story of Billy and Jimmy Lee, twin brothers trained in the fighting style of Sou-Setsu-Ken.","Avatar":"img/dd1pc1.gif?size=50x50&set=set1","iframe_URL":"https://archive.org/embed/msdos_Double_Dragon_1988"},

{"Game_Title":"Teenage Mutant Ninja Turtles - Manhattan Missions","Publisher":"Konami","Year_Published":1991,"Description":"Shredder will assume control of New York City in 48 hours. The Ninja Turtles must stop him and at the same time fight even the lesser crimes taking place in New York City. No surprise that each of these crimes leads to Shredder.","Avatar":"img/teenage-mutant-ninja-turtles-manhattan-missions_6.png?size=50x50&set=set1","iframe_URL":"https://archive.org/embed/msdos_Teenage_Mutant_Ninja_Turtles_-_Manhattan_Missions_1991"},

{"Game_Title":"Disney's Aladdin","Publisher":"Virgin Interactive Entertainment","Year_Published":1994,"Description":"The game from Virgin based on the 1992 animated Disney film is a side-scrolling platformer. The player controls Aladdin, who must make his way through several levels based on locations from the movie: from the streets and rooftops of Agrabah, the Cave of Wonders and the Sultan's dungeon to the final confrontation in Grand Vizier Jafar's palace.","Avatar":"img/maxresdefault.jpg?size=50x50&set=set1","iframe_URL":"https://archive.org/embed/msdos_Disneys_Aladdin_1994"}]